### ISSUE TITLE
Filtering with --spoof-for

### ISSUE THREAD

**Issue by dadevel** [RedTeamPentesting/pretender#3]
Hi,
first of all thanks for this great tool :D

I have a feature request regarding filtering with `--spoof-for`.

Following example:

~~~
# pretender --verbose --interface ens18 --no-lnr --spoof-for 192.168.2.2
Pretender by RedTeam Pentesting built from git commit 69d85ac239
Listening on interface: ens18
IPv4 relayed to: 192.168.2.12
IPv6 relayed to: fe80::8f6:4eff:fef4:f415
Answering queries from: 192.168.2.2

23:44:35 [DNS] listening via TCP on [fe80::8f6:4eff:fef4:f415%ens18]:53
23:44:35 [DNS] listening via UDP on [fe80::8f6:4eff:fef4:f415%ens18]:53
23:44:35 [DHCPv6] listening via UDP on [ff02::1:2%ens18]:547
23:44:36 [RA] sending router advertisement on ens18
23:44:51 [DHCPv6] ignoring DHCP SOLICIT request from fe80::d09b:746d:4510:5d8c (win2016.arasaka.local, 192.168.2.2): host not in spoof-for list
~~~

I think `pretender` should answer the DHCPv6 request, because it knows that `fe80::d09b:746d:4510:5d8c` belongs to the allowed address `192.168.2.2`.
Otherwise allowing only specific IPs is quiet cumbersome because you have to know the IPv6 address in beforehand.

Another case is this:

~~~
# pretender --verbose --interface ens18 --no-lnr --spoof-for win2016.arasaka.local
Pretender by RedTeam Pentesting built from git commit 69d85ac239
Listening on interface: ens18
IPv4 relayed to: 192.168.2.12
IPv6 relayed to: fe80::8f6:4eff:fef4:f415
Answering queries from: win2016.arasaka.local (192.168.2.2)

23:39:10 [DHCPv6] listening via UDP on [ff02::1:2%ens18]:547
23:39:10 [DNS] listening via TCP on [fe80::8f6:4eff:fef4:f415%ens18]:53
23:39:10 [DNS] listening via UDP on [fe80::8f6:4eff:fef4:f415%ens18]:53
23:39:11 [RA] sending router advertisement on ens18
23:39:38 [DHCPv6] responding to SOLICIT from fe80::d09b:746d:4510:5d8c (win2016.arasaka.local, 192.168.2.2) by assigning IPv6 "fe80::8000:c66d:7e7b:5e75"
23:39:39 [DHCPv6] responding to REQUEST from fe80::d09b:746d:4510:5d8c (win2016.arasaka.local, 192.168.2.2) by assigning DNS server and IPv6 "fe80::8000:c66d:7e7b:5e75"
23:39:39 [DNS] ignoring query for "win2016.arasaka.local" (SOA) from fe80::8000:c66d:7e7b:5e75 (192.168.2.2): host address and name not in spoof-for list
~~~

Here it would be nice if the query from `fe80::8000:c66d:7e7b:5e75 (192.168.2.2)` would be answered, because `pretender` knows that `fe80::8000:c66d:7e7b:5e75` belongs to `192.168.2.2` which in turn belongs to `win2016.arasaka.local`.

**Comment by erikgeiser** [comment]
Hi, i'm glad you like `pretender`. I myself have been annoyed by this this, too, so I have thought about this a lot already. However, I have come to the conclusion that the filtering rules should not utilize the data in the parentheses ("host info") for the following reasons:

* The info in parentheses ("host info") is infered through various methods by the logger. The only purpose of this function is to provide additional insight into what's going on and to make it easier to match name resolution events to events captured by other tools such as `ntlmrelayx.py`. This is why the implementation of both features (filter rules and host info) are quite isolated of each other. 
* The info is infered on best-effort basis. For example, it currently only works on Windows and Linux, the name resolution and ARP lookup timeouts are also quite short in order to not delay logging the event for too long and it is performed asynchronously after having received a request. That's why some of the info may not be available or it may only be available after having already previously received a request. This could result in race conditions when say a IPv6 mDNS request is received when the host info logic has not yet matched the IPv6 address to an IPv4 address. In contrast, filtering rules should be very reliable as deciding who to attack and who not to attack is a very deliberate decision, therefore it should be very precise.
* The decision whether or not to answer a request has to be fast for local name resolution methdos such that the attacked system receives the spoofed response before the legitimate response. Waiting for asyncronous information gathering (when the info is not yet cached) would significantly delay the response.

**Comment by dadevel** [comment]
Hi, thanks for detailed explanation.
Wouldn't it be possible to build a lookup table in beforehand? E.g. take the IPs or FQDNs specified with `--spoof-for` and do the ARP, DNS, etc. lookups on startup.
If the implementation takes to much time or is otherwise unfeasible you can close the issue. After all this was just a quick idea that popped into my head :D

**Comment by rtpt-erikgeiser** [comment]
If you specify a domain, it will do a DNS lookup for IPv4/IPv6 addresses and add the results to the list (they will also appear in stdout). However, ARP and NDP lookups are not performed as this is platform specific and I don't want critical functionality like `--spoof`, `--spoof-for`, `--dont-spoof` and `--dont-spoof-for` to be platform specific and potentially unreliable.

These lookups are currently implemented by running the shell commands and parsing the output because otherwise they'd require additional privileges. So when the parsing fails it would not be too bad for 'nice to know' info but it would be bad for making a decision what to answer.

I'll close this issue now, but I'm glad we discussed it :wink:
